import type { RunResult, TestResult } from '../schemas/index.js';
import { formatDuration } from '../utils/format-duration.js';

/**
 * Configuration for building a GitHub PR comment body.
 */
export interface GitHubCommentPayload {
  readonly body: string;
  readonly owner: string;
  readonly repo: string;
  readonly issueNumber: number;
  readonly commitSha: string;
}

/**
 * Options for building a GitHub PR comment.
 */
export interface GitHubCommentOptions {
  readonly runResult: RunResult;
  readonly owner: string;
  readonly repo: string;
  readonly prNumber: number;
  readonly reportUrl?: string;
}

/** Marker used to identify and update existing sorry-currents comments */
const COMMENT_MARKER = '<!-- sorry-currents-report -->';

/**
 * Build the markdown body for a GitHub PR comment.
 * Pure function — no I/O.
 */
export function buildGitHubCommentBody(options: GitHubCommentOptions): GitHubCommentPayload {
  const { runResult, owner, repo, prNumber, reportUrl } = options;

  const statusIcon = runResult.status === 'passed' ? '✅' : '❌';
  const lines: string[] = [
    COMMENT_MARKER,
    `## ${statusIcon} sorry-currents Test Results`,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Total  | ${runResult.totalTests} |`,
    `| Passed | ${runResult.passedTests} ✅ |`,
    `| Failed | ${runResult.failedTests} ❌ |`,
    `| Flaky  | ${runResult.flakyTests} ⚠️ |`,
    `| Skipped | ${runResult.skippedTests} |`,
    `| Duration | ${formatDuration(runResult.duration)} |`,
    `| Shards | ${runResult.shardCount} |`,
    '',
  ];

  const failed = runResult.tests.filter(
    (t: TestResult) => t.status === 'failed' || t.status === 'timedOut',
  );
  if (failed.length > 0) {
    lines.push('### ❌ Failed Tests', '');
    lines.push('| Test | Error | Duration |');
    lines.push('|------|-------|----------|');
    for (const t of failed) {
      const errorMsg = t.errors[0]?.message ?? 'Unknown error';
      // Truncate long error messages for table readability
      const truncated = errorMsg.length > 80 ? errorMsg.slice(0, 77) + '...' : errorMsg;
      const escaped = truncated.replace(/\|/g, '\\|').replace(/\n/g, ' ');
      lines.push(
        `| \`${t.file} > ${t.title}\` | ${escaped} | ${formatDuration(t.duration)} |`,
      );
    }
    lines.push('');
  }

  const flaky = runResult.tests.filter((t: TestResult) => t.isFlaky);
  if (flaky.length > 0) {
    lines.push('### ⚠️ Flaky Tests (passed on retry)', '');
    lines.push('| Test | Retries |');
    lines.push('|------|---------|');
    for (const t of flaky) {
      lines.push(`| \`${t.file} > ${t.title}\` | ${t.retries} |`);
    }
    lines.push('');
  }

  const footer: string[] = [];
  if (reportUrl) {
    footer.push(`📊 [Full Report](${reportUrl})`);
  }
  footer.push('*Generated by [sorry-currents](https://github.com/nicholasgriffintn/sorry-currents)*');
  lines.push(footer.join(' | '));
  lines.push('');

  return {
    body: lines.join('\n'),
    owner,
    repo,
    issueNumber: prNumber,
    commitSha: runResult.git.commit,
  };
}

/**
 * Extract the comment marker for finding existing comments to update.
 */
export function getCommentMarker(): string {
  return COMMENT_MARKER;
}
