/**
 * Typed error codes for all expected failure modes.
 * Enum is acceptable here — internal-only code, not serialized data.
 */
export enum ErrorCode {
  // File system
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_PARSE_ERROR = 'FILE_PARSE_ERROR',
  FILE_WRITE_ERROR = 'FILE_WRITE_ERROR',
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  // Validation
  SCHEMA_VALIDATION = 'SCHEMA_VALIDATION',
  INVALID_CONFIG = 'INVALID_CONFIG',
  INVALID_CLI_ARGS = 'INVALID_CLI_ARGS',

  // Playwright integration
  PLAYWRIGHT_NOT_FOUND = 'PLAYWRIGHT_NOT_FOUND',
  PLAYWRIGHT_VERSION = 'PLAYWRIGHT_VERSION',
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  NO_TESTS_FOUND = 'NO_TESTS_FOUND',

  // Shard balancing
  NO_TIMING_DATA = 'NO_TIMING_DATA',
  INVALID_SHARD_COUNT = 'INVALID_SHARD_COUNT',
  SHARD_PLAN_MISMATCH = 'SHARD_PLAN_MISMATCH',

  // CI / Environment
  CI_NOT_DETECTED = 'CI_NOT_DETECTED',
  MISSING_ENV_VAR = 'MISSING_ENV_VAR',
  GIT_NOT_AVAILABLE = 'GIT_NOT_AVAILABLE',

  // Integrations
  GITHUB_API_ERROR = 'GITHUB_API_ERROR',
  SLACK_WEBHOOK_ERROR = 'SLACK_WEBHOOK_ERROR',
  WEBHOOK_ERROR = 'WEBHOOK_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',

  // Internal
  UNEXPECTED = 'UNEXPECTED',
}
